// ============================================================
// EXAMOTECA — Banco de preguntas original
// ============================================================
// Contenido escrito específicamente para esta plataforma (no son
// reactivos de exámenes reales de ninguna universidad). Cada
// pregunta incluye explicación. Organizado por materia (usa los
// mismos ids que CATEGORIES en App.jsx).
//
// Estructura: Q(id, materia, pregunta, [opciones], indiceCorrecta, explicacion)

const Q = (id, materia, pregunta, opciones, correcta, explicacion) => ({
  id, materia, pregunta, opciones, correcta, explicacion,
});

export const QUESTION_BANK_FULL = [

/* ============================================================
   MATEMÁTICAS
   ============================================================ */
Q("mat001","matematicas","¿Cuánto es 7 × 8?",["54","56","58","64"],1,"7 multiplicado por 8 es 56."),
Q("mat002","matematicas","¿Cuál es la derivada de f(x) = x³?",["x²","3x²","3x³","x³/3"],1,"Con la regla de potencias, la derivada de xⁿ es n·x^(n-1); para x³ resulta 3x²."),
Q("mat003","matematicas","Según el teorema de Pitágoras, en un triángulo rectángulo se cumple que:",["a + b = c","a² + b² = c²","a × b = c","a² - b² = c²"],1,"El teorema de Pitágoras relaciona los catetos (a, b) y la hipotenusa (c) mediante a² + b² = c²."),
Q("mat004","matematicas","¿Cuál es el área de un círculo de radio r?",["2πr","πr²","πr","2πr²"],1,"El área de un círculo se calcula como π multiplicado por el radio al cuadrado."),
Q("mat005","matematicas","¿Cuál es el valor aproximado de π?",["2.71","3.14","1.61","4.13"],1,"π (pi) es aproximadamente 3.1416, la relación entre la circunferencia y el diámetro de un círculo."),
Q("mat006","matematicas","Resuelve: 2x + 5 = 15",["x = 5","x = 10","x = 7.5","x = 20"],0,"Restando 5 en ambos lados: 2x = 10; dividiendo entre 2: x = 5."),
Q("mat007","matematicas","¿Cuál es la pendiente de la recta y = 3x + 2?",["2","3","5","1/3"],1,"En la forma y = mx + b, m representa la pendiente; aquí m = 3."),
Q("mat008","matematicas","¿Cuánto suman los ángulos internos de cualquier triángulo?",["90°","180°","270°","360°"],1,"La suma de los ángulos internos de un triángulo siempre es 180°."),
Q("mat009","matematicas","¿Cuál es la raíz cuadrada de 144?",["11","12","13","14"],1,"12 × 12 = 144, por lo tanto la raíz cuadrada de 144 es 12."),
Q("mat010","matematicas","¿Cuánto es 5 factorial (5!)?",["25","60","120","720"],2,"5! = 5×4×3×2×1 = 120."),
Q("mat011","matematicas","¿Cuál es el logaritmo base 10 de 100?",["1","2","10","100"],1,"log₁₀(100) = 2 porque 10² = 100."),
Q("mat012","matematicas","En la fórmula general para resolver ecuaciones cuadráticas ax²+bx+c=0, la fórmula es:",["x = -b/a", "x = (-b ± √(b²-4ac)) / 2a", "x = b² - 4ac", "x = a + b + c"],1,"La fórmula general (o resolvente) despeja x usando los coeficientes a, b y c del polinomio cuadrático."),
Q("mat013","matematicas","¿Cuánto vale el seno de 90°?",["0","0.5","1","-1"],2,"sen(90°) = 1, el valor máximo de la función seno."),
Q("mat014","matematicas","¿Cuál es la integral de 2x dx?",["x²","x² + C","2x² + C","x + C"],1,"La integral de 2x respecto a x es x², más la constante de integración C."),
Q("mat015","matematicas","¿Cuál es el máximo común divisor (MCD) de 12 y 18?",["2","3","6","9"],2,"El mayor número que divide exactamente tanto a 12 como a 18 es 6."),
Q("mat016","matematicas","¿Cuál es el mínimo común múltiplo (MCM) de 4 y 6?",["10","12","20","24"],1,"El menor múltiplo común de 4 y 6 es 12."),
Q("mat017","matematicas","¿Cuánto es el 20% de 50?",["5","10","15","20"],1,"20% de 50 = 0.20 × 50 = 10."),
Q("mat018","matematicas","¿Cuál es el desarrollo de (a + b)²?",["a² + b²","a² + 2ab + b²","2a + 2b","a² - b²"],1,"El binomio al cuadrado se desarrolla como a² + 2ab + b²."),
Q("mat019","matematicas","¿Cuántos grados tiene un ángulo recto?",["45°","90°","180°","360°"],1,"Un ángulo recto mide exactamente 90°."),
Q("mat020","matematicas","¿Cuál es la mediana del conjunto {2, 4, 6, 8, 10}?",["4","5","6","8"],2,"Con los datos ordenados, la mediana es el valor central: 6."),
Q("mat021","matematicas","Al lanzar un dado justo, ¿cuál es la probabilidad de obtener un 4?",["1/2","1/4","1/6","1/3"],2,"El dado tiene 6 caras igualmente probables, así que la probabilidad de cualquier cara específica es 1/6."),
Q("mat022","matematicas","Resuelve el sistema: x + y = 10, x - y = 2",["x=4, y=6","x=6, y=4","x=5, y=5","x=8, y=2"],1,"Sumando ambas ecuaciones: 2x=12, x=6; sustituyendo, y=4."),
Q("mat023","matematicas","¿Cuál es el volumen de un cubo con lado de 3 cm?",["9 cm³","18 cm³","27 cm³","81 cm³"],2,"El volumen de un cubo es lado³; 3³ = 27 cm³."),
Q("mat024","matematicas","¿Cuánto vale i² en los números complejos?",["1","-1","0","i"],1,"Por definición, la unidad imaginaria i cumple que i² = -1."),
Q("mat025","matematicas","En la sucesión aritmética 2, 5, 8, 11..., ¿cuál es la diferencia común?",["2","3","5","6"],1,"Cada término se obtiene sumando 3 al anterior (5-2=3, 8-5=3)."),
Q("mat026","matematicas","¿Cuál es el resultado de simplificar 3/4 + 1/4?",["1/2","3/8","1","4/8"],2,"Al tener el mismo denominador, se suman los numeradores: 3/4+1/4 = 4/4 = 1."),
Q("mat027","matematicas","¿Qué tipo de número es √2?",["Natural","Entero","Racional","Irracional"],3,"√2 no puede expresarse como fracción exacta de dos enteros; es un número irracional."),
Q("mat028","matematicas","¿Cuál es el perímetro de un cuadrado de lado 5 cm?",["10 cm","15 cm","20 cm","25 cm"],2,"El perímetro de un cuadrado es 4 veces el lado: 4×5=20 cm."),
Q("mat029","matematicas","La función f(x) = x² es una función:",["Lineal","Cuadrática","Cúbica","Exponencial"],1,"Una función con la variable elevada al cuadrado como término de mayor grado es cuadrática."),
Q("mat030","matematicas","¿Cuánto es log(1)?",["0","1","10","Indefinido"],0,"El logaritmo de 1 en cualquier base siempre es 0, porque cualquier número elevado a 0 es 1."),

/* ============================================================
   FÍSICA
   ============================================================ */
Q("fis001","fisica","¿Cuál es la unidad de medida de la fuerza en el Sistema Internacional?",["Joule","Newton","Watt","Pascal"],1,"La fuerza se mide en Newtons (N), en honor a Isaac Newton."),
Q("fis002","fisica","La velocidad se define como:",["Fuerza por tiempo","Distancia entre tiempo","Masa por aceleración","Trabajo entre tiempo"],1,"La velocidad es la relación entre la distancia recorrida y el tiempo empleado."),
Q("fis003","fisica","¿Cuál es el valor aproximado de la aceleración de la gravedad en la Tierra?",["9.8 m/s²","3.8 m/s²","1.6 m/s²","98 m/s²"],0,"La aceleración de la gravedad en la superficie terrestre es aproximadamente 9.8 m/s²."),
Q("fis004","fisica","La segunda ley de Newton se expresa como:",["F = m/a","F = m × a","F = m + a","F = a/m"],1,"La segunda ley de Newton establece que la fuerza es igual a la masa multiplicada por la aceleración."),
Q("fis005","fisica","La ley de Ohm se expresa como:",["V = I/R","V = I × R","V = R/I","I = V + R"],1,"La ley de Ohm relaciona voltaje, corriente y resistencia: V = I × R."),
Q("fis006","fisica","¿En qué unidad se mide la energía en el Sistema Internacional?",["Newton","Watt","Joule","Volt"],2,"La energía se mide en Joules (J)."),
Q("fis007","fisica","¿Cuál es aproximadamente la velocidad de la luz en el vacío?",["3×10⁵ m/s","3×10⁶ m/s","3×10⁸ m/s","3×10¹⁰ m/s"],2,"La luz viaja en el vacío a aproximadamente 3×10⁸ metros por segundo."),
Q("fis008","fisica","La primera ley de la termodinámica establece que:",["El calor siempre fluye del frío al caliente","La energía no se crea ni se destruye, solo se transforma","La entropía siempre disminuye","La temperatura es constante en un sistema aislado"],1,"Es el principio de conservación de la energía aplicado a sistemas termodinámicos."),
Q("fis009","fisica","¿En qué unidad se mide la potencia?",["Joule","Newton","Watt","Pascal"],2,"La potencia, que es energía por unidad de tiempo, se mide en Watts (W)."),
Q("fis010","fisica","La energía cinética de un objeto se calcula como:",["m × v","1/2 × m × v²","m × g × h","F × d"],1,"La energía cinética es igual a un medio de la masa por la velocidad al cuadrado."),
Q("fis011","fisica","La tercera ley de Newton establece que:",["Todo cuerpo permanece en reposo salvo que actúe una fuerza","A toda acción corresponde una reacción igual y opuesta","La fuerza es proporcional a la masa","La energía se conserva"],1,"Es la ley de acción y reacción: las fuerzas siempre aparecen en pares iguales y opuestos."),
Q("fis012","fisica","¿En qué unidad se mide la carga eléctrica?",["Amperio","Voltio","Coulomb","Ohm"],2,"La carga eléctrica se mide en Coulombs (C)."),
Q("fis013","fisica","La densidad de un objeto se calcula como:",["Masa × volumen","Masa entre volumen","Volumen entre masa","Masa entre peso"],1,"La densidad es la masa dividida entre el volumen que ocupa un cuerpo."),
Q("fis014","fisica","La presión se define como:",["Fuerza por área","Fuerza entre área","Masa por área","Masa entre área"],1,"La presión es la fuerza aplicada dividida entre el área sobre la que actúa."),
Q("fis015","fisica","¿En qué unidad se mide la frecuencia?",["Newton","Hertz","Watt","Joule"],1,"La frecuencia se mide en Hertz (Hz), que representa ciclos por segundo."),
Q("fis016","fisica","La ley de conservación del momento lineal establece que, en ausencia de fuerzas externas:",["El momento total del sistema permanece constante","La energía cinética siempre aumenta","La velocidad siempre disminuye","La masa se transforma en energía"],0,"En un sistema aislado, el momento lineal total se conserva antes y después de una interacción."),
Q("fis017","fisica","La refracción de la luz ocurre cuando:",["La luz se refleja en un espejo","La luz cambia de dirección al pasar entre medios distintos","La luz se absorbe completamente","La luz se polariza"],1,"La refracción es el cambio de dirección de la luz al pasar de un medio a otro con distinta densidad óptica."),
Q("fis018","fisica","La energía potencial gravitatoria depende de:",["Solo la masa","Solo la velocidad","La masa, la gravedad y la altura","Solo el tiempo"],2,"La energía potencial gravitatoria se calcula como m × g × h (masa, gravedad, altura)."),
Q("fis019","fisica","¿Cuál es la unidad de resistencia eléctrica?",["Amperio","Voltio","Ohm","Watt"],2,"La resistencia eléctrica se mide en Ohms (Ω)."),
Q("fis020","fisica","En caída libre (sin fricción del aire), la aceleración de un objeto es:",["Cero","Constante","Variable, aumenta con el tiempo","Variable, disminuye con el tiempo"],1,"En caída libre ideal, la única fuerza es la gravedad, que produce una aceleración constante."),
Q("fis021","fisica","El periodo de un péndulo simple depende principalmente de:",["Su masa y su color","Su longitud y la gravedad","Su velocidad inicial","Su temperatura"],1,"El periodo de un péndulo simple depende de la longitud de la cuerda y de la aceleración de la gravedad, no de la masa."),
Q("fis022","fisica","Según la ley de Boyle, a temperatura constante, la presión de un gas es:",["Directamente proporcional a su volumen","Inversamente proporcional a su volumen","Independiente del volumen","Igual a su volumen"],1,"La ley de Boyle establece que, a temperatura constante, presión y volumen de un gas son inversamente proporcionales."),
Q("fis023","fisica","Dos cargas eléctricas del mismo signo:",["Se atraen","Se repelen","No interactúan","Se anulan"],1,"Cargas del mismo signo se repelen; cargas de signo opuesto se atraen."),
Q("fis024","fisica","El sonido viaja más rápido en:",["El vacío","El aire","El agua","Un sólido como el acero"],3,"El sonido se propaga más rápido en medios más densos y rígidos como los sólidos, en comparación con líquidos o gases."),
Q("fis025","fisica","La energía mecánica total de un sistema es la suma de:",["Energía térmica y calor","Energía cinética y energía potencial","Energía eléctrica y magnética","Masa y velocidad"],1,"La energía mecánica es la suma de la energía cinética (movimiento) y la energía potencial (posición)."),

/* ============================================================
   QUÍMICA
   ============================================================ */
Q("qui001","quimica","El número atómico de un elemento indica:",["El número de neutrones","El número de protones","El número de electrones de valencia","La masa atómica"],1,"El número atómico corresponde al número de protones en el núcleo del átomo."),
Q("qui002","quimica","La tabla periódica organiza a los elementos principalmente según:",["Su color","Su número atómico","Su estado de agregación","Su año de descubrimiento"],1,"Los elementos están ordenados de forma creciente según su número atómico."),
Q("qui003","quimica","¿Cuál es la fórmula química del agua?",["CO2","H2O","O2","H2O2"],1,"El agua está formada por dos átomos de hidrógeno y uno de oxígeno: H2O."),
Q("qui004","quimica","En la escala de pH, un valor de 7 se considera:",["Ácido","Básico","Neutro","No tiene sentido"],2,"Un pH de 7 corresponde a una sustancia neutra, como el agua pura."),
Q("qui005","quimica","¿A qué corresponde aproximadamente el número de Avogadro?",["6.022 × 10²³","3.14 × 10⁸","9.8 × 10¹","1.6 × 10⁻¹⁹"],0,"El número de Avogadro (6.022×10²³) indica el número de partículas en un mol de sustancia."),
Q("qui006","quimica","Un enlace iónico se forma por:",["Compartición de electrones","Transferencia de electrones entre átomos","Fusión de núcleos atómicos","Repulsión entre protones"],1,"En un enlace iónico, un átomo cede electrones y otro los recibe, formando iones de carga opuesta que se atraen."),
Q("qui007","quimica","Un enlace covalente se forma por:",["Transferencia de electrones","Compartición de electrones entre átomos","Atracción entre iones","Fuerzas gravitacionales"],1,"En el enlace covalente, dos átomos comparten uno o más pares de electrones."),
Q("qui008","quimica","La reacción entre un ácido y una base produce:",["Solo agua","Sal y agua","Solo un gas","Un metal puro"],1,"Una reacción de neutralización entre ácido y base típicamente produce una sal y agua."),
Q("qui009","quimica","Los gases nobles se caracterizan por ser:",["Muy reactivos","Químicamente inertes en su mayoría","Metales pesados","Ácidos fuertes"],1,"Los gases nobles (grupo 18) tienen su capa de valencia completa, por lo que reaccionan muy poco."),
Q("qui010","quimica","Dos isótopos de un mismo elemento tienen:",["Distinto número de protones","El mismo número de protones y distinto número de neutrones","El mismo número de neutrones y distinto número de protones","Distinta identidad química"],1,"Los isótopos comparten el número de protones (mismo elemento) pero difieren en el número de neutrones."),
Q("qui011","quimica","Una reacción de combustión requiere principalmente:",["Nitrógeno","Oxígeno","Hidrógeno","Dióxido de carbono"],1,"La combustión es una reacción de oxidación rápida que requiere oxígeno como comburente."),
Q("qui012","quimica","La masa molar aproximada del agua (H2O) es:",["2 g/mol","16 g/mol","18 g/mol","32 g/mol"],2,"Sumando las masas atómicas: 2(1)+16 = 18 g/mol aproximadamente."),
Q("qui013","quimica","La oxidación de un átomo implica:",["Ganancia de electrones","Pérdida de electrones","Pérdida de protones","Ganancia de neutrones"],1,"La oxidación se define como la pérdida de electrones por parte de un átomo o ion."),
Q("qui014","quimica","Un catalizador en una reacción química:",["Se consume completamente","Aumenta la energía de activación","Acelera la reacción sin consumirse","Detiene la reacción"],2,"Un catalizador acelera una reacción química disminuyendo la energía de activación, sin consumirse en el proceso."),
Q("qui015","quimica","¿Cuáles son los estados de agregación clásicos de la materia?",["Sólido, líquido, gaseoso y plasma","Ácido, base y neutro","Orgánico e inorgánico","Metálico y no metálico"],0,"Los cuatro estados clásicos son sólido, líquido, gaseoso y plasma."),
Q("qui016","quimica","Balancear una ecuación química es necesario para respetar:",["La ley de la gravedad","La ley de conservación de la masa","La ley de los gases ideales","La ley de Ohm"],1,"Una ecuación balanceada asegura que el número de átomos de cada elemento sea igual en reactivos y productos."),
Q("qui017","quimica","Los metales alcalinos (grupo 1 de la tabla periódica) se caracterizan por ser:",["Muy poco reactivos","Altamente reactivos","Gases a temperatura ambiente","Elementos radiactivos siempre"],1,"Los metales alcalinos son muy reactivos, especialmente con el agua, debido a que tienen un solo electrón de valencia."),
Q("qui018","quimica","La química orgánica se enfoca principalmente en el estudio de compuestos basados en:",["Silicio","Carbono","Hierro","Azufre"],1,"La química orgánica estudia los compuestos que contienen carbono, generalmente combinado con hidrógeno."),
Q("qui019","quimica","El nombre común de NaCl es:",["Bicarbonato","Sal de mesa","Vinagre","Cal"],1,"NaCl (cloruro de sodio) es la sal común de mesa."),
Q("qui020","quimica","Una reacción endotérmica se caracteriza por:",["Liberar calor al entorno","Absorber calor del entorno","No involucrar energía","Ser siempre explosiva"],1,"En una reacción endotérmica, el sistema absorbe energía calorífica de su entorno."),
Q("qui021","quimica","Una reacción exotérmica se caracteriza por:",["Absorber calor","Liberar calor al entorno","Detener la reacción","Requerir un catalizador siempre"],1,"En una reacción exotérmica, se libera energía en forma de calor hacia el entorno."),
Q("qui022","quimica","Los electrones de valencia son:",["Los electrones del núcleo","Los electrones de la capa más externa de un átomo","Todos los electrones del átomo","Solo los electrones libres"],1,"Los electrones de valencia, ubicados en la capa más externa, determinan la reactividad química del átomo."),
Q("qui023","quimica","La diferencia entre una mezcla y un compuesto es que:",["Una mezcla siempre es homogénea","Un compuesto puede separarse por medios físicos simples","Un compuesto tiene proporciones fijas de sus elementos, una mezcla no","No hay diferencia real"],2,"En un compuesto, los elementos están unidos químicamente en proporciones fijas; en una mezcla, la proporción puede variar y se separa por medios físicos."),
Q("qui024","quimica","El papel tornasol se usa para detectar:",["Temperatura","Acidez o basicidad de una sustancia","Densidad","Concentración de sal"],1,"El papel tornasol cambia de color (rojo en medio ácido, azul en medio básico) para indicar el pH aproximado."),
Q("qui025","quimica","Un polímero es una molécula formada por:",["Un solo átomo","La repetición de unidades más pequeñas (monómeros)","Solo metales","Solo gases nobles"],1,"Un polímero es una macromolécula formada por la repetición de unidades estructurales llamadas monómeros."),

/* ============================================================
   BIOLOGÍA
   ============================================================ */
Q("bio001","biologia","Según la teoría celular, la célula es:",["Solo parte de los seres vivos complejos","La unidad básica estructural y funcional de los seres vivos","Exclusiva de los animales","Un tipo de tejido"],1,"La teoría celular establece que la célula es la unidad estructural y funcional básica de todos los seres vivos."),
Q("bio002","biologia","La estructura del ADN se describe como:",["Una sola cadena lineal","Una doble hélice","Un anillo simple siempre","Una red tridimensional"],1,"El ADN tiene una estructura de doble hélice, propuesta por Watson y Crick."),
Q("bio003","biologia","¿Cuál es la función principal de la mitocondria?",["Síntesis de proteínas","Producción de energía (ATP)","Almacenamiento de agua","Digestión celular"],1,"La mitocondria realiza la respiración celular, generando la mayor parte del ATP de la célula."),
Q("bio004","biologia","La fotosíntesis es el proceso mediante el cual las plantas:",["Consumen oxígeno para producir energía","Convierten la luz solar en energía química","Absorben nutrientes del suelo únicamente","Se reproducen asexualmente"],1,"La fotosíntesis convierte la energía luminosa en energía química almacenada en moléculas de glucosa."),
Q("bio005","biologia","Un gen es:",["Una proteína completa","Un segmento de ADN que codifica información hereditaria","Un tipo de célula","Un organelo celular"],1,"Un gen es una secuencia específica de ADN que contiene la información para producir una proteína o rasgo."),
Q("bio006","biologia","La mitosis da como resultado:",["Cuatro células con la mitad de cromosomas","Dos células hijas genéticamente idénticas a la madre","Una célula con el doble de cromosomas","Gametos"],1,"La mitosis es un tipo de división celular que produce dos células hijas idénticas entre sí y a la célula madre."),
Q("bio007","biologia","La meiosis tiene como resultado principal:",["Células somáticas idénticas","Gametos con la mitad de la información genética","El doble de cromosomas","La muerte celular programada"],1,"La meiosis reduce a la mitad el número de cromosomas para formar los gametos (óvulos y espermatozoides)."),
Q("bio008","biologia","La teoría de la selección natural fue propuesta principalmente por:",["Gregor Mendel","Charles Darwin","Louis Pasteur","Robert Hooke"],1,"Charles Darwin propuso la teoría de la evolución por selección natural."),
Q("bio009","biologia","Un ecosistema está formado por:",["Solo los seres vivos de una zona","Los seres vivos y su ambiente físico interactuando entre sí","Solo el ambiente físico","Solo las plantas de una región"],1,"Un ecosistema incluye tanto a los organismos vivos (biocenosis) como al ambiente físico que habitan (biotopo)."),
Q("bio010","biologia","En una cadena alimenticia, los organismos que producen su propio alimento se llaman:",["Consumidores","Descomponedores","Productores","Depredadores"],2,"Los productores (como las plantas) generan su propio alimento mediante fotosíntesis, siendo la base de la cadena alimenticia."),
Q("bio011","biologia","El orden correcto de la clasificación taxonómica, de más general a más específico, es:",["Especie, género, familia, orden, clase, filo, reino","Reino, filo, clase, orden, familia, género, especie","Filo, reino, clase, especie, género, familia, orden","Género, especie, familia, reino"],1,"La jerarquía taxonómica va de lo más amplio (reino) a lo más específico (especie)."),
Q("bio012","biologia","Una enzima es una molécula que actúa como:",["Fuente de energía principal","Catalizador biológico","Material genético","Estructura de soporte celular"],1,"Las enzimas son proteínas que aceleran las reacciones químicas dentro de los organismos, actuando como catalizadores."),
Q("bio013","biologia","La homeostasis se refiere a:",["El crecimiento descontrolado de células","La capacidad de un organismo de mantener su equilibrio interno","La reproducción asexual","La extinción de una especie"],1,"La homeostasis es el mantenimiento de un ambiente interno estable a pesar de los cambios externos."),
Q("bio014","biologia","¿Cuál es una diferencia entre vertebrados e invertebrados?",["Los invertebrados no tienen tejidos", "Los vertebrados poseen columna vertebral y los invertebrados no", "Los vertebrados son siempre acuáticos", "No existe ninguna diferencia relevante"],1,"Los vertebrados se caracterizan por poseer una columna vertebral, estructura ausente en los invertebrados."),
Q("bio015","biologia","La ósmosis es el movimiento de:",["Proteínas a través de una membrana","Agua a través de una membrana semipermeable","Iones mediante transporte activo","ADN entre células"],1,"La ósmosis describe el paso de agua a través de una membrana semipermeable desde una zona de menor a mayor concentración de soluto."),
Q("bio016","biologia","Los cromosomas se encuentran principalmente en:",["El citoplasma","El núcleo celular","La membrana plasmática","Las mitocondrias exclusivamente"],1,"Los cromosomas, formados por ADN y proteínas, se localizan en el núcleo de la célula."),
Q("bio017","biologia","Una diferencia entre ADN y ARN es que el ARN:",["Es siempre bicatenario","Contiene uracilo en lugar de timina","No contiene información genética","Solo existe en bacterias"],1,"El ARN utiliza uracilo en lugar de timina, y suele ser monocatenario, a diferencia del ADN."),
Q("bio018","biologia","La ecuación general de la fotosíntesis produce, además de glucosa:",["Dióxido de carbono","Oxígeno","Nitrógeno","Metano"],1,"La fotosíntesis, usando CO2, agua y luz, produce glucosa y libera oxígeno como subproducto."),
Q("bio019","biologia","El número de cromosomas en una célula humana normal es:",["23","44","46","48"],2,"Las células somáticas humanas tienen 46 cromosomas, organizados en 23 pares."),
Q("bio020","biologia","La relación en la que ambas especies se benefician mutuamente se llama:",["Parasitismo","Comensalismo","Mutualismo","Depredación"],2,"En el mutualismo, ambas especies obtienen un beneficio de la interacción."),
Q("bio021","biologia","¿Cuál es la función principal de los glóbulos rojos?",["Combatir infecciones","Transportar oxígeno","Coagular la sangre","Producir anticuerpos"],1,"Los glóbulos rojos (eritrocitos) transportan oxígeno desde los pulmones hacia los tejidos."),
Q("bio022","biologia","Una diferencia entre la célula vegetal y la célula animal es que la célula vegetal tiene:",["Núcleo","Mitocondrias","Pared celular","Membrana plasmática"],2,"La célula vegetal posee una pared celular rígida de celulosa que la célula animal no tiene."),
Q("bio023","biologia","La evolución biológica se describe como:",["Un cambio repentino en una sola generación","Un cambio gradual en las características heredables de una población a lo largo del tiempo","La reproducción asexual de bacterias","Un tipo de metabolismo celular"],1,"La evolución es el proceso de cambio gradual en las características heredables de las poblaciones a través de generaciones."),
Q("bio024","biologia","La biodiversidad se refiere a:",["La cantidad de agua en un ecosistema","La variedad de formas de vida en un lugar determinado","El tamaño de una población","La velocidad de reproducción de una especie"],1,"La biodiversidad es la variedad de especies y ecosistemas presentes en un área o en el planeta."),
Q("bio025","biologia","Las vacunas funcionan principalmente porque:",["Eliminan directamente al patógeno","Estimulan al sistema inmunológico a generar memoria contra un patógeno","Sustituyen a los antibióticos","Curan enfermedades ya presentes"],1,"Las vacunas exponen al sistema inmune a un antígeno para que genere memoria inmunológica y responda más rápido ante una infección real."),

/* ============================================================
   MEDICINA (contenido educativo general, no consejo clínico)
   ============================================================ */
Q("med001","medicina","¿Cuántas cámaras tiene el corazón humano?",["2","3","4","5"],2,"El corazón humano tiene cuatro cámaras: dos aurículas y dos ventrículos."),
Q("med002","medicina","La temperatura corporal normal promedio de un humano adulto es aproximadamente:",["35°C","37°C","39°C","41°C"],1,"La temperatura corporal normal se considera alrededor de 37°C, con variación individual."),
Q("med003","medicina","¿Cuáles son los grupos sanguíneos principales del sistema ABO?",["A, B, C, D","A, B, AB, O","X, Y, Z","Alfa, Beta, Gamma"],1,"El sistema ABO clasifica la sangre en los grupos A, B, AB y O."),
Q("med004","medicina","La insulina, hormona que regula el azúcar en sangre, es producida por:",["El hígado","El páncreas","Los riñones","La tiroides"],1,"La insulina es producida por las células beta de los islotes de Langerhans en el páncreas."),
Q("med005","medicina","Los antibióticos son eficaces principalmente contra:",["Virus","Bacterias","Hongos únicamente","Todos los microorganismos por igual"],1,"Los antibióticos actúan sobre bacterias; no son eficaces contra infecciones virales."),
Q("med006","medicina","La hipertensión se refiere a:",["Baja presión arterial","Presión arterial elevada de forma sostenida","Niveles bajos de azúcar en sangre","Frecuencia cardiaca lenta"],1,"La hipertensión es la elevación sostenida de la presión arterial por encima de valores normales."),
Q("med007","medicina","La diabetes mellitus se caracteriza principalmente por:",["Exceso de glóbulos rojos","Dificultad para regular los niveles de glucosa en sangre","Presión arterial baja","Deficiencia de vitamina C"],1,"La diabetes es un trastorno metabólico caracterizado por niveles elevados de glucosa en sangre debido a problemas con la insulina."),
Q("med008","medicina","Los rayos X se utilizan principalmente en medicina para:",["Medir la temperatura corporal","Obtener imágenes de estructuras internas como los huesos","Medir la presión arterial","Analizar el pH de la sangre"],1,"Los rayos X permiten obtener imágenes de estructuras densas como los huesos, útiles en el diagnóstico."),
Q("med009","medicina","El estetoscopio es un instrumento médico utilizado para:",["Medir la temperatura","Escuchar sonidos internos como el corazón y los pulmones","Medir la glucosa","Tomar muestras de sangre"],1,"El estetoscopio amplifica los sonidos internos del cuerpo, como los latidos cardiacos y la respiración."),
Q("med010","medicina","En términos anatómicos, el término 'anterior' se refiere a:",["La parte de atrás del cuerpo","La parte delantera del cuerpo","La parte superior","La parte inferior"],1,"En anatomía, anterior indica la posición hacia el frente del cuerpo."),
Q("med011","medicina","La fiebre es, en general:",["Un signo de que el cuerpo está bajando su temperatura","Una respuesta del cuerpo asociada frecuentemente a procesos infecciosos o inflamatorios","Un síntoma exclusivo de enfermedades graves","Lo mismo que la hipotermia"],1,"La fiebre es un aumento de la temperatura corporal, frecuentemente asociado a una respuesta inmunológica ante una infección."),
Q("med012","medicina","La función principal de los glóbulos blancos es:",["Transportar oxígeno","Participar en la defensa inmunológica del cuerpo","Coagular la sangre","Transportar nutrientes"],1,"Los glóbulos blancos (leucocitos) forman parte del sistema inmunológico y ayudan a combatir infecciones."),
Q("med013","medicina","La frecuencia cardiaca normal en reposo de un adulto sano suele estar alrededor de:",["20-40 latidos por minuto","60-100 latidos por minuto","150-180 latidos por minuto","200-250 latidos por minuto"],1,"En reposo, la frecuencia cardiaca normal de un adulto se ubica generalmente entre 60 y 100 latidos por minuto."),
Q("med014","medicina","¿Cuál es una función principal del riñón?",["Producir insulina","Filtrar la sangre y formar orina","Digerir las grasas","Producir glóbulos rojos exclusivamente"],1,"Los riñones filtran la sangre para eliminar desechos y producir orina, regulando también el equilibrio de líquidos."),
Q("med015","medicina","El hígado cumple, entre otras, la función de:",["Producir insulina","Desintoxicar sustancias y producir bilis","Bombear la sangre","Producir hormonas tiroideas"],1,"El hígado desintoxica sustancias del organismo y produce bilis, necesaria para digerir grasas."),
Q("med016","medicina","La epidemiología estudia principalmente:",["La anatomía de órganos individuales","La distribución y los determinantes de las enfermedades en poblaciones","El tratamiento farmacológico individual","La genética molecular"],1,"La epidemiología analiza cómo se distribuyen las enfermedades en las poblaciones y qué factores las determinan."),
Q("med017","medicina","La diferencia entre epidemia y pandemia es que la pandemia:",["Afecta a un área geográfica más amplia, incluso a nivel mundial","Es menos grave","Solo afecta a animales","No involucra microorganismos"],0,"Una pandemia es la propagación mundial de una enfermedad, mientras que una epidemia suele limitarse a una región."),
Q("med018","medicina","La deficiencia de vitamina C se asocia clásicamente con:",["Raquitismo","Escorbuto","Anemia falciforme","Beriberi"],1,"La carencia prolongada de vitamina C provoca escorbuto, caracterizado por sangrado de encías y debilidad."),
Q("med019","medicina","Los anticuerpos son producidos principalmente por:",["Los glóbulos rojos","Las células plasmáticas (derivadas de linfocitos B)","Las plaquetas","El hígado"],1,"Las células plasmáticas, que derivan de los linfocitos B, son las encargadas de producir anticuerpos."),
Q("med020","medicina","La promoción de la salud se enfoca principalmente en:",["Tratar enfermedades ya avanzadas","Prevenir enfermedades y fomentar estilos de vida saludables","Realizar cirugías","Diagnosticar enfermedades raras"],1,"La promoción de la salud busca prevenir enfermedades y fomentar hábitos saludables antes de que aparezcan padecimientos."),
Q("med021","medicina","El sistema linfático participa principalmente en:",["La digestión de grasas exclusivamente","El drenaje de líquido y la respuesta inmunológica","La producción de hormonas sexuales","El bombeo de sangre"],1,"El sistema linfático drena el exceso de líquido intersticial y participa activamente en la respuesta inmune."),
Q("med022","medicina","Una vacuna típicamente contiene:",["Solo antibióticos","Un antígeno que estimula la respuesta inmune","Únicamente vitaminas","Glucosa concentrada"],1,"Las vacunas contienen antígenos (microorganismos atenuados, inactivados o fragmentos) que entrenan al sistema inmunológico."),
Q("med023","medicina","El órgano responsable de filtrar y almacenar sangre, además de participar en la respuesta inmune, es:",["El páncreas","El bazo","La vesícula biliar","La glándula tiroides"],1,"El bazo filtra la sangre y participa en la respuesta inmunológica del organismo."),
Q("med024","medicina","La primera inmunoglobulina producida en una respuesta inmune primaria es:",["IgG","IgM","IgA","IgE"],1,"La IgM es típicamente la primera inmunoglobulina producida ante un primer contacto con un antígeno."),
Q("med025","medicina","Un electrocardiograma (ECG) se utiliza para evaluar:",["La función pulmonar","La actividad eléctrica del corazón","Los niveles de glucosa","La función renal"],1,"El electrocardiograma registra la actividad eléctrica del corazón para evaluar su funcionamiento."),

/* ============================================================
   ANATOMÍA
   ============================================================ */
Q("ana001","anatomia","¿Aproximadamente cuántos huesos tiene el esqueleto de un adulto humano?",["106","156","206","256"],2,"El esqueleto humano adulto está formado por aproximadamente 206 huesos."),
Q("ana002","anatomia","¿Cuál es el hueso más largo del cuerpo humano?",["Húmero","Tibia","Fémur","Radio"],2,"El fémur, ubicado en el muslo, es el hueso más largo y fuerte del cuerpo humano."),
Q("ana003","anatomia","La estructura ósea que protege al cerebro es:",["La columna vertebral","El cráneo","La pelvis","El esternón"],1,"El cráneo forma una cavidad ósea que rodea y protege al cerebro."),
Q("ana004","anatomia","¿Cuáles son los tres tipos principales de tejido muscular?",["Estriado, liso y cardiaco","Óseo, cartilaginoso y adiposo","Epitelial, conectivo y nervioso","Rojo, blanco y mixto"],0,"Los tres tipos de músculo son el esquelético (estriado), el liso y el cardiaco."),
Q("ana005","anatomia","¿Cuál es la parte más grande del encéfalo humano?",["Cerebelo","Cerebro (con sus hemisferios)","Tronco encefálico","Médula espinal"],1,"El cerebro, dividido en hemisferios, es la porción más grande y voluminosa del encéfalo."),
Q("ana006","anatomia","El cerebelo tiene como función principal:",["Regular la temperatura corporal","Coordinar el movimiento y el equilibrio","Producir hormonas","Filtrar la sangre"],1,"El cerebelo se encarga de la coordinación motora, el equilibrio y la precisión de los movimientos."),
Q("ana007","anatomia","La médula espinal forma parte de:",["El sistema digestivo","El sistema nervioso central","El sistema circulatorio","El sistema endocrino"],1,"Junto con el encéfalo, la médula espinal constituye el sistema nervioso central."),
Q("ana008","anatomia","El corazón se localiza principalmente en:",["El hipocondrio derecho","El mediastino, ligeramente hacia la izquierda","La fosa ilíaca","El epigastrio derecho"],1,"El corazón se ubica en el mediastino, entre los pulmones, con una ligera inclinación hacia la izquierda."),
Q("ana009","anatomia","La principal función de los pulmones es:",["Filtrar la sangre","El intercambio de gases (oxígeno y dióxido de carbono)","Producir glóbulos rojos","Digerir nutrientes"],1,"Los pulmones son el sitio principal del intercambio gaseoso entre el aire inhalado y la sangre."),
Q("ana010","anatomia","¿Qué órgano se encarga de secretar ácido para digerir los alimentos?",["El hígado","El estómago","El páncreas","El intestino delgado"],1,"El estómago secreta ácido clorhídrico y enzimas para descomponer los alimentos."),
Q("ana011","anatomia","El órgano interno más grande del cuerpo humano es:",["El corazón","El hígado","El estómago","El bazo"],1,"El hígado es el órgano interno de mayor tamaño en el cuerpo humano."),
Q("ana012","anatomia","Los riñones tienen forma característica de:",["Estrella","Frijol","Disco","Espiral"],1,"Los riñones tienen una característica forma de frijol o judía."),
Q("ana013","anatomia","¿Cuál es el órgano más grande del cuerpo humano en superficie?",["El hígado","Los pulmones","La piel","El intestino"],2,"La piel, considerando toda su extensión, es el órgano más grande del cuerpo humano."),
Q("ana014","anatomia","La capa más externa de la piel se llama:",["Dermis","Epidermis","Hipodermis","Fascia"],1,"La epidermis es la capa más superficial y externa de la piel."),
Q("ana015","anatomia","Una articulación es el punto donde:",["Se unen dos músculos","Se encuentran dos o más huesos","Se cruzan dos nervios","Confluyen dos vasos sanguíneos"],1,"Las articulaciones son las estructuras donde se unen dos o más huesos, permitiendo o restringiendo el movimiento."),
Q("ana016","anatomia","El cartílago es un tipo de tejido:",["Óseo duro","Conectivo flexible","Nervioso","Muscular"],1,"El cartílago es un tejido conectivo flexible que proporciona soporte y amortiguación en articulaciones y otras estructuras."),
Q("ana017","anatomia","Los tendones conectan:",["Hueso con hueso","Músculo con hueso","Nervio con músculo","Piel con músculo"],1,"Los tendones son estructuras fibrosas que conectan los músculos a los huesos."),
Q("ana018","anatomia","Los ligamentos conectan principalmente:",["Músculo con hueso","Hueso con hueso","Nervio con hueso","Piel con hueso"],1,"Los ligamentos son estructuras fibrosas que conectan un hueso con otro, estabilizando las articulaciones."),
Q("ana019","anatomia","El diafragma es un músculo fundamental para:",["La digestión","La respiración","La circulación sanguínea","La visión"],1,"El diafragma es el principal músculo respiratorio, encargado de la inhalación y exhalación."),
Q("ana020","anatomia","La tráquea es una estructura que conduce:",["Alimento hacia el estómago","Aire hacia los pulmones","Sangre hacia el corazón","Orina hacia la vejiga"],1,"La tráquea es el conducto que lleva el aire desde la laringe hacia los bronquios y pulmones."),
Q("ana021","anatomia","El esófago conecta:",["La faringe con el estómago","La boca con la faringe","El estómago con el intestino delgado","La nariz con la laringe"],0,"El esófago es el conducto muscular que transporta el bolo alimenticio desde la faringe hasta el estómago."),
Q("ana022","anatomia","La pelvis ósea tiene como función principal:",["Producir hormonas","Sostener y proteger órganos abdominales inferiores","Filtrar la sangre","Producir glóbulos blancos"],1,"La pelvis proporciona soporte estructural y protección a los órganos de la parte inferior del abdomen."),
Q("ana023","anatomia","La retina, ubicada en el ojo, es responsable de:",["Enfocar la luz","Detectar la luz y convertirla en señales nerviosas","Producir lágrimas","Proteger el ojo de impactos"],1,"La retina contiene células fotorreceptoras que convierten la luz en señales eléctricas enviadas al cerebro."),
Q("ana024","anatomia","La cóclea es una estructura del:",["Ojo","Oído interno","Sistema digestivo","Sistema respiratorio"],1,"La cóclea, en el oído interno, es fundamental para la audición, al transformar las vibraciones sonoras en impulsos nerviosos."),
Q("ana025","anatomia","La columna vertebral está formada aproximadamente por:",["12 vértebras","24 vértebras","33 vértebras (en el niño; algunas se fusionan en el adulto)","50 vértebras"],2,"La columna vertebral tiene alrededor de 33 vértebras en el desarrollo, aunque varias se fusionan (sacro y cóccix) en la edad adulta."),

/* ============================================================
   FISIOLOGÍA
   ============================================================ */
Q("fsg001","fisiologia","El ciclo cardiaco se compone principalmente de:",["Inspiración y espiración","Sístole y diástole","Filtración y reabsorción","Excitación e inhibición"],1,"El ciclo cardiaco alterna entre la sístole (contracción) y la diástole (relajación) del corazón."),
Q("fsg002","fisiologia","El sistema nervioso se divide principalmente en:",["Sistema óseo y muscular","Sistema nervioso central y periférico","Sistema digestivo y respiratorio","Sistema circulatorio y linfático"],1,"El sistema nervioso se organiza en sistema nervioso central (encéfalo y médula espinal) y sistema nervioso periférico (nervios)."),
Q("fsg003","fisiologia","La neurona es considerada:",["La unidad funcional del sistema muscular","La unidad funcional básica del sistema nervioso","Un tipo de célula sanguínea","Parte del sistema digestivo"],1,"La neurona es la célula especializada que transmite señales eléctricas y químicas en el sistema nervioso."),
Q("fsg004","fisiologia","La sinapsis es:",["Un tipo de hueso","El punto de comunicación entre dos neuronas","Un órgano del sistema digestivo","Un tipo de célula sanguínea"],1,"La sinapsis es la unión funcional entre dos neuronas donde se transmite la señal nerviosa."),
Q("fsg005","fisiologia","Las hormonas son:",["Células especializadas","Mensajeros químicos que viajan por la sangre","Estructuras óseas","Tipos de tejido conectivo"],1,"Las hormonas son sustancias químicas producidas por glándulas que regulan funciones en órganos distantes."),
Q("fsg006","fisiologia","La presión arterial se mide comúnmente en unidades de:",["Litros por minuto","Milímetros de mercurio (mmHg)","Grados Celsius","Latidos por minuto"],1,"La presión arterial se expresa en milímetros de mercurio (mmHg), como en la lectura 120/80."),
Q("fsg007","fisiologia","El peristaltismo se refiere a:",["Contracciones musculares que impulsan el contenido del tubo digestivo","La producción de saliva","La filtración renal","La contracción del corazón"],0,"El peristaltismo son ondas de contracción muscular que impulsan el alimento a lo largo del tubo digestivo."),
Q("fsg008","fisiologia","La filtración inicial de la sangre en el riñón ocurre en:",["El túbulo colector","La cápsula de Bowman","La vejiga","La uretra"],1,"La cápsula de Bowman, que rodea al glomérulo, es donde ocurre la filtración inicial de la sangre en la nefrona."),
Q("fsg009","fisiologia","Un reflejo se caracteriza por ser:",["Una respuesta voluntaria y lenta","Una respuesta involuntaria y rápida","Un proceso exclusivamente hormonal","Un tipo de memoria a largo plazo"],1,"Un reflejo es una respuesta rápida e involuntaria del sistema nervioso ante un estímulo."),
Q("fsg010","fisiologia","La glándula tiroides regula principalmente:",["La digestión","El metabolismo del cuerpo","La coagulación sanguínea","La visión"],1,"La tiroides produce hormonas que regulan el metabolismo corporal."),
Q("fsg011","fisiologia","La adrenalina se asocia comúnmente con la respuesta de:",["Digestión y reposo","Lucha o huida (estrés agudo)","Sueño profundo","Crecimiento óseo"],1,"La adrenalina es liberada en situaciones de estrés y prepara al cuerpo para la respuesta de lucha o huida."),
Q("fsg012","fisiologia","La contracción muscular ocurre principalmente por el deslizamiento de los filamentos de:",["Colágeno y queratina","Actina y miosina","ADN y ARN","Glucosa y glucógeno"],1,"La contracción muscular se basa en el deslizamiento de los filamentos de actina y miosina dentro de la fibra muscular."),
Q("fsg013","fisiologia","Las plaquetas participan principalmente en:",["El transporte de oxígeno","La coagulación de la sangre","La producción de anticuerpos","La digestión de grasas"],1,"Las plaquetas son fundamentales en el proceso de coagulación sanguínea para detener hemorragias."),
Q("fsg014","fisiologia","La molécula considerada la principal fuente de energía utilizable por la célula es:",["El ADN","El ATP","El colesterol","La hemoglobina"],1,"El ATP (adenosín trifosfato) es la principal molécula de almacenamiento y transferencia de energía en la célula."),
Q("fsg015","fisiologia","El páncreas cumple una función dual porque:",["Solo produce hormonas","Tiene función endocrina (hormonas) y exocrina (enzimas digestivas)","Solo produce enzimas digestivas","No participa en la digestión"],1,"El páncreas es una glándula mixta: su porción endocrina secreta hormonas como insulina, y su porción exocrina secreta enzimas digestivas."),
Q("fsg016","fisiologia","La respuesta inmune innata se caracteriza por:",["Ser específica para cada patógeno","Actuar de forma rápida y general ante distintos patógenos","Requerir varias semanas para desarrollarse","Depender exclusivamente de anticuerpos"],1,"La inmunidad innata es la primera línea de defensa, de acción rápida y no específica, en contraste con la inmunidad adaptativa."),
Q("fsg017","fisiologia","Un mecanismo de retroalimentación negativa en el cuerpo sirve para:",["Amplificar continuamente una respuesta","Mantener el equilibrio, revirtiendo un cambio detectado","Producir enfermedades","Detener la reproducción celular"],1,"La retroalimentación negativa es un mecanismo homeostático que contrarresta un cambio, ayudando a mantener el equilibrio interno."),
Q("fsg018","fisiologia","El sistema nervioso autónomo se divide en:",["Central y periférico","Simpático y parasimpático","Sensitivo y motor","Voluntario e involuntario únicamente"],1,"El sistema nervioso autónomo tiene dos ramas: la simpática (activación) y la parasimpática (relajación)."),
Q("fsg019","fisiologia","La digestión de los alimentos combina procesos:",["Solo mecánicos","Solo químicos","Mecánicos y químicos","Ninguno de los anteriores"],2,"La digestión involucra tanto procesos mecánicos (masticación, movimientos) como químicos (enzimas)."),
Q("fsg020","fisiologia","El sistema excretor tiene como función principal:",["Producir hormonas sexuales","Eliminar desechos metabólicos del cuerpo","Producir glóbulos rojos","Coordinar el movimiento"],1,"El sistema excretor, principalmente a través de los riñones, elimina los productos de desecho del metabolismo."),

/* ============================================================
   HISTORIA
   ============================================================ */
Q("his001","historia","¿En qué año comenzó la Revolución Francesa?",["1776","1789","1804","1848"],1,"La Revolución Francesa comenzó en 1789 con la toma de la Bastilla."),
Q("his002","historia","¿En qué año terminó la Segunda Guerra Mundial?",["1939","1942","1945","1950"],2,"La Segunda Guerra Mundial concluyó en 1945, con la rendición de Alemania y posteriormente de Japón."),
Q("his003","historia","La independencia de México inició en 1810 encabezada principalmente por:",["Benito Juárez","Miguel Hidalgo","Porfirio Díaz","Emiliano Zapata"],1,"Miguel Hidalgo inició el movimiento de independencia de México en 1810 con el llamado Grito de Dolores."),
Q("his004","historia","¿En qué año llegó Cristóbal Colón a América?",["1492","1500","1521","1810"],0,"Cristóbal Colón llegó a América en 1492, en su primer viaje patrocinado por la corona española."),
Q("his005","historia","¿En qué año cayó el Muro de Berlín?",["1975","1985","1989","1995"],2,"El Muro de Berlín cayó en 1989, marcando el fin simbólico de la Guerra Fría en Europa."),
Q("his006","historia","Las pirámides del Antiguo Egipto se construyeron principalmente como:",["Templos para el pueblo","Tumbas monumentales para faraones","Fortalezas militares","Centros comerciales"],1,"Las pirámides egipcias fueron construidas principalmente como tumbas monumentales para los faraones."),
Q("his007","historia","Julio César fue una figura clave de:",["La antigua Grecia","El Imperio Romano","El Imperio Bizantino","El Imperio Persa"],1,"Julio César fue un destacado líder militar y político de la Roma antigua."),
Q("his008","historia","El Renacimiento se caracterizó por:",["Un rechazo total al arte","Un renovado interés en el arte, la ciencia y la cultura clásica","La expansión del feudalismo","El fin del comercio internacional"],1,"El Renacimiento fue un periodo de renovado interés en las artes, las ciencias y la cultura clásica grecorromana."),
Q("his009","historia","La Revolución Industrial se originó principalmente en:",["Francia","Gran Bretaña","España","Rusia"],1,"La Revolución Industrial tuvo su origen en Gran Bretaña a finales del siglo XVIII."),
Q("his010","historia","La Guerra Fría se caracterizó principalmente por la rivalidad entre:",["Francia y Alemania","Estados Unidos y la Unión Soviética","China y Japón","España y Portugal"],1,"La Guerra Fría fue un periodo de tensión geopolítica entre Estados Unidos y la Unión Soviética tras la Segunda Guerra Mundial."),
Q("his011","historia","La Carta Magna, considerada un antecedente del constitucionalismo, fue firmada en:",["1066","1215","1492","1789"],1,"La Carta Magna fue firmada en Inglaterra en 1215, limitando el poder del rey."),
Q("his012","historia","La independencia de Estados Unidos se declaró en:",["1776","1789","1810","1865"],0,"Estados Unidos declaró su independencia de Gran Bretaña en 1776."),
Q("his013","historia","La Revolución Mexicana comenzó en:",["1810","1857","1910","1917"],2,"La Revolución Mexicana inició en 1910, en gran parte como reacción al gobierno de Porfirio Díaz."),
Q("his014","historia","La antigua Grecia es considerada la cuna de:",["El feudalismo","La democracia","El Imperio Romano","El cristianismo"],1,"La antigua Grecia, particularmente Atenas, es reconocida como cuna de los primeros sistemas democráticos."),
Q("his015","historia","La Primera Guerra Mundial comenzó en:",["1905","1914","1918","1929"],1,"La Primera Guerra Mundial comenzó en 1914, tras el asesinato del archiduque Francisco Fernando."),
Q("his016","historia","La capital del Imperio Azteca era:",["Teotihuacán","Tenochtitlán","Chichén Itzá","Monte Albán"],1,"Tenochtitlán, ubicada donde hoy está la Ciudad de México, fue la capital del Imperio Azteca."),
Q("his017","historia","La conquista de México-Tenochtitlán fue liderada por:",["Francisco Pizarro","Hernán Cortés","Cristóbal Colón","Fernando de Magallanes"],1,"Hernán Cortés lideró la expedición española que resultó en la caída de Tenochtitlán en 1521."),
Q("his018","historia","La Organización de las Naciones Unidas (ONU) fue fundada en:",["1919","1939","1945","1960"],2,"La ONU fue fundada en 1945, al concluir la Segunda Guerra Mundial, con el objetivo de mantener la paz internacional."),
Q("his019","historia","La Gran Depresión estuvo marcada por la caída de la bolsa de valores en:",["1918","1929","1939","1945"],1,"La Gran Depresión inició con el colapso de la bolsa de valores de Nueva York en 1929."),
Q("his020","historia","Napoleón Bonaparte fue:",["Rey de España","Emperador de Francia","Zar de Rusia","Rey de Inglaterra"],1,"Napoleón Bonaparte se coronó Emperador de Francia a inicios del siglo XIX."),
Q("his021","historia","Mahatma Gandhi es reconocido principalmente por:",["Liderar una revolución armada","Promover la resistencia no violenta por la independencia de la India","Fundar el Imperio Británico","Iniciar la Revolución Industrial"],1,"Gandhi promovió la resistencia civil no violenta como estrategia para lograr la independencia de la India."),
Q("his022","historia","En la Segunda Guerra Mundial, las potencias del Eje estaban formadas principalmente por:",["Estados Unidos, Reino Unido y Francia","Alemania, Italia y Japón","Unión Soviética, China y Cuba","España, Portugal y Grecia"],1,"El Eje estaba conformado principalmente por Alemania, Italia y Japón, enfrentando a los Aliados."),
Q("his023","historia","La caída de Constantinopla ante el Imperio Otomano ocurrió en:",["1215","1453","1521","1789"],1,"Constantinopla cayó ante los otomanos en 1453, un evento considerado el fin de la Edad Media para muchos historiadores."),
Q("his024","historia","La imprenta de tipos móviles es atribuida principalmente a:",["Leonardo da Vinci","Johannes Gutenberg","Galileo Galilei","Isaac Newton"],1,"Johannes Gutenberg desarrolló la imprenta de tipos móviles en el siglo XV, revolucionando la difusión del conocimiento."),
Q("his025","historia","La Constitución mexicana actualmente vigente en su origen data de:",["1824","1857","1917","1936"],2,"La Constitución Política de los Estados Unidos Mexicanos fue promulgada en 1917, tras la Revolución Mexicana."),

/* ============================================================
   INGENIERÍA
   ============================================================ */
Q("ing001","ingenieria","El esfuerzo mecánico (stress) se calcula como:",["Fuerza multiplicada por área","Fuerza entre área","Área entre fuerza","Masa entre fuerza"],1,"El esfuerzo mecánico se define como la fuerza aplicada dividida entre el área sobre la que actúa."),
Q("ing002","ingenieria","El diseño asistido por computadora se conoce comúnmente por las siglas:",["CAM","CAD","CNC","CAE"],1,"CAD (Computer-Aided Design) se refiere al diseño asistido por computadora."),
Q("ing003","ingenieria","La ingeniería civil se enfoca principalmente en:",["El diseño de circuitos electrónicos","El diseño y construcción de infraestructura como puentes y edificios","La programación de software","La producción de alimentos"],1,"La ingeniería civil se dedica al diseño, construcción y mantenimiento de infraestructura como carreteras, puentes y edificios."),
Q("ing004","ingenieria","La ciencia de materiales estudia principalmente:",["El comportamiento del mercado","Las propiedades y aplicaciones de los materiales","Los procesos contables","El comportamiento del consumidor"],1,"La ciencia de materiales investiga las propiedades físicas y químicas de los materiales y sus posibles aplicaciones."),
Q("ing005","ingenieria","La mecánica de fluidos estudia:",["El comportamiento de los sólidos rígidos","El comportamiento de los líquidos y gases en reposo o movimiento","Las reacciones químicas","Los circuitos eléctricos"],1,"La mecánica de fluidos analiza el comportamiento de líquidos y gases, tanto en reposo como en movimiento."),
Q("ing006","ingenieria","Las leyes de la termodinámica son fundamentales para el diseño de:",["Puentes peatonales","Motores y sistemas de generación de energía","Sistemas contables","Estructuras de datos"],1,"Las leyes de la termodinámica rigen la conversión de energía, siendo esenciales en el diseño de motores y sistemas energéticos."),
Q("ing007","ingenieria","La ingeniería mecánica se enfoca principalmente en:",["El diseño de sistemas legales","El diseño y análisis de máquinas y sistemas mecánicos","La contabilidad de costos","El estudio de idiomas"],1,"La ingeniería mecánica se dedica al diseño, análisis y mantenimiento de máquinas y sistemas mecánicos."),
Q("ing008","ingenieria","La ingeniería eléctrica se ocupa principalmente de:",["El estudio de la electricidad, la electrónica y el electromagnetismo","El diseño de edificios","La producción agrícola","La administración de personal"],1,"La ingeniería eléctrica estudia y aplica los principios de la electricidad, la electrónica y el electromagnetismo."),
Q("ing009","ingenieria","Las energías renovables incluyen principalmente:",["Petróleo, carbón y gas natural","Solar, eólica e hidráulica","Solo la energía nuclear","Ninguna fuente de energía natural"],1,"Las energías renovables provienen de fuentes naturales que se regeneran, como el sol, el viento y el agua."),
Q("ing010","ingenieria","La resistencia a la tracción de un material mide:",["Su capacidad de flotar","Su resistencia a ser estirado o jalado sin romperse","Su color","Su temperatura de fusión únicamente"],1,"La resistencia a la tracción indica la capacidad de un material para resistir fuerzas que tienden a estirarlo."),
Q("ing011","ingenieria","El torque en ingeniería mecánica se refiere a:",["Una fuerza lineal","Una fuerza de rotación aplicada sobre un eje","La temperatura de un motor","El voltaje de un circuito"],1,"El torque es una medida de la fuerza de rotación aplicada a un objeto, como un eje o una tuerca."),
Q("ing012","ingenieria","Una viga, en ingeniería estructural, es un elemento diseñado principalmente para:",["Resistir la flexión y soportar cargas transversales","Almacenar líquidos","Generar electricidad","Medir la temperatura"],0,"Las vigas son elementos estructurales que resisten esfuerzos de flexión y soportan cargas transversales."),
Q("ing013","ingenieria","Un circuito eléctrico se define como:",["Un dibujo arquitectónico","Un camino cerrado por el que puede fluir la corriente eléctrica","Un tipo de motor","Un material aislante"],1,"Un circuito eléctrico es una trayectoria cerrada que permite el flujo de corriente eléctrica."),
Q("ing014","ingenieria","Un prototipo en el proceso de diseño de ingeniería es:",["El producto final terminado y comercializado","Un modelo o muestra inicial de un producto para pruebas y evaluación","Un contrato legal","Un tipo de material"],1,"Un prototipo es una versión preliminar de un producto, utilizada para probar y validar su diseño antes de la producción final."),
Q("ing015","ingenieria","El factor de seguridad en un diseño de ingeniería se utiliza para:",["Reducir costos de material sin ningún margen","Considerar un margen adicional frente a incertidumbres y cargas no previstas","Eliminar toda necesidad de pruebas","Aumentar el peso de una estructura sin razón"],1,"El factor de seguridad añade un margen de diseño para cubrir incertidumbres, variaciones de carga o imperfecciones no previstas."),
Q("ing016","ingenieria","La robótica combina principalmente conocimientos de:",["Solo contabilidad y finanzas","Ingeniería mecánica, electrónica e informática","Solo derecho y administración","Solo biología"],1,"La robótica es un campo interdisciplinario que integra ingeniería mecánica, electrónica e informática."),
Q("ing017","ingenieria","La ingeniería sostenible busca principalmente:",["Ignorar el impacto ambiental de los proyectos","Diseñar soluciones considerando el impacto ambiental y social a largo plazo","Maximizar costos sin ninguna justificación","Evitar el uso de cualquier tecnología nueva"],1,"La ingeniería sostenible considera el impacto ambiental, social y económico de los proyectos a largo plazo."),
Q("ing018","ingenieria","Un plano o 'blueprint' en ingeniería es:",["Un contrato legal","Un dibujo técnico detallado de un diseño","Un informe financiero","Un manual de recursos humanos"],1,"Un blueprint o plano es una representación técnica y detallada de un diseño de ingeniería o arquitectura."),
Q("ing019","ingenieria","Una pared de carga (load-bearing wall) en una construcción se caracteriza por:",["No tener ninguna función estructural","Soportar el peso estructural del edificio, además de dividir espacios","Ser exclusivamente decorativa","Servir solo para aislar el ruido"],1,"Una pared de carga soporta parte del peso estructural de la edificación, a diferencia de un muro simplemente divisorio."),
Q("ing020","ingenieria","La eficiencia de una máquina se define como:",["La relación entre la energía de salida útil y la energía de entrada","El peso total de la máquina","El precio de la máquina","El color de sus componentes"],0,"La eficiencia mide qué proporción de la energía de entrada se convierte en trabajo útil, siendo siempre igual o menor al 100%."),

/* ============================================================
   INFORMÁTICA
   ============================================================ */
Q("inf001","informatica","Un algoritmo se define como:",["Un tipo de hardware","Una secuencia ordenada de pasos para resolver un problema","Un lenguaje de programación específico","Un tipo de base de datos"],1,"Un algoritmo es un conjunto ordenado y finito de pasos que permite resolver un problema o realizar una tarea."),
Q("inf002","informatica","En programación, una variable se utiliza para:",["Ejecutar un programa","Almacenar un valor que puede cambiar durante la ejecución de un programa","Diseñar una interfaz gráfica","Conectar a internet"],1,"Una variable es un espacio en memoria identificado por un nombre, que almacena un valor que puede modificarse."),
Q("inf003","informatica","Un bucle o ciclo (loop) en programación sirve para:",["Terminar un programa inmediatamente","Repetir un bloque de código mientras se cumpla una condición","Eliminar variables","Conectar bases de datos"],1,"Un bucle permite ejecutar repetidamente un bloque de instrucciones mientras se cumpla una condición determinada."),
Q("inf004","informatica","El sistema binario utilizado por las computadoras se basa en:",["Diez dígitos (0 al 9)","Dos dígitos (0 y 1)","Letras del alfabeto","Símbolos matemáticos exclusivamente"],1,"El sistema binario representa la información usando únicamente los dígitos 0 y 1."),
Q("inf005","informatica","La memoria RAM se caracteriza por ser:",["Permanente, incluso sin energía eléctrica","Volátil, perdiendo su contenido al apagar el equipo","Un tipo de disco duro externo","Exclusiva para almacenar el sistema operativo"],1,"La memoria RAM es volátil: su contenido se pierde cuando el equipo se apaga."),
Q("inf006","informatica","El CPU (unidad central de procesamiento) se encarga principalmente de:",["Almacenar archivos de forma permanente","Ejecutar las instrucciones y procesar los datos de un programa","Mostrar imágenes en pantalla exclusivamente","Conectar dispositivos periféricos únicamente"],1,"El CPU es el componente que procesa las instrucciones y realiza los cálculos necesarios para ejecutar los programas."),
Q("inf007","informatica","Una base de datos se utiliza principalmente para:",["Diseñar gráficos","Almacenar y organizar información de manera estructurada","Ejecutar videojuegos exclusivamente","Reemplazar al sistema operativo"],1,"Una base de datos organiza y almacena información de forma estructurada para facilitar su consulta y gestión."),
Q("inf008","informatica","HTML es un lenguaje utilizado principalmente para:",["Programar aplicaciones móviles nativas","Estructurar el contenido de las páginas web","Gestionar bases de datos","Controlar hardware directamente"],1,"HTML (HyperText Markup Language) es el lenguaje de marcado utilizado para estructurar el contenido de las páginas web."),
Q("inf009","informatica","El sistema operativo tiene como función principal:",["Diseñar páginas web","Gestionar los recursos de hardware y software de una computadora","Reemplazar la memoria RAM","Sustituir al procesador"],1,"El sistema operativo administra los recursos de hardware y software, sirviendo de intermediario entre el usuario y la máquina."),
Q("inf010","informatica","Un arreglo (array) en programación es:",["Un único valor aislado","Una colección ordenada de elementos del mismo tipo, accesibles por índice","Un tipo de base de datos relacional","Un componente físico de la computadora"],1,"Un arreglo es una estructura de datos que almacena una colección ordenada de elementos, accesibles mediante un índice."),
Q("inf011","informatica","Una función en programación es:",["Un bloque de código reutilizable diseñado para realizar una tarea específica","Un tipo de variable","Un componente de hardware","Un protocolo de red"],0,"Una función agrupa un conjunto de instrucciones reutilizables que realizan una tarea específica dentro de un programa."),
Q("inf012","informatica","La programación orientada a objetos se basa principalmente en el uso de:",["Solo variables globales","Clases y objetos","Únicamente bucles","Solo bases de datos"],1,"La programación orientada a objetos organiza el código en clases (plantillas) y objetos (instancias) con atributos y comportamientos."),
Q("inf013","informatica","Una dirección IP sirve principalmente para:",["Identificar un dispositivo dentro de una red","Almacenar contraseñas","Ejecutar programas","Diseñar interfaces gráficas"],0,"Una dirección IP identifica de forma única a un dispositivo dentro de una red."),
Q("inf014","informatica","Un compilador se encarga de:",["Traducir el código fuente a lenguaje de máquina","Diseñar bases de datos","Conectar dispositivos Bluetooth","Editar imágenes"],0,"Un compilador traduce el código escrito por un programador (código fuente) a instrucciones que la computadora puede ejecutar."),
Q("inf015","informatica","La depuración (debugging) en programación consiste en:",["Escribir nuevo código desde cero siempre","Identificar y corregir errores en un programa","Eliminar completamente un programa","Traducir el código a otro idioma humano"],1,"La depuración es el proceso de encontrar y corregir errores (bugs) dentro de un programa."),
Q("inf016","informatica","La computación en la nube (cloud computing) se refiere a:",["El uso exclusivo de computadoras personales sin conexión","La entrega de servicios de cómputo (almacenamiento, procesamiento, etc.) a través de internet","Un tipo de virus informático","Un lenguaje de programación"],1,"La computación en la nube ofrece servicios informáticos (almacenamiento, servidores, bases de datos) a través de internet."),
Q("inf017","informatica","La encriptación de datos tiene como principal objetivo:",["Hacer más lento un sistema sin ningún beneficio","Proteger la confidencialidad de la información","Aumentar el tamaño de los archivos sin razón","Eliminar archivos de forma permanente"],1,"La encriptación transforma la información para que solo pueda ser leída por quienes cuenten con la clave adecuada, protegiendo su confidencialidad."),
Q("inf018","informatica","La recursividad en programación ocurre cuando:",["Una función se llama a sí misma para resolver un problema","Un programa nunca termina de ejecutarse","Se eliminan todas las variables de un programa","Un archivo se elimina automáticamente"],0,"La recursividad es una técnica en la que una función se invoca a sí misma para resolver subproblemas más pequeños."),
Q("inf019","informatica","SQL es un lenguaje utilizado principalmente para:",["Diseñar interfaces gráficas de usuario","Gestionar y consultar bases de datos relacionales","Programar videojuegos exclusivamente","Configurar redes inalámbricas"],1,"SQL (Structured Query Language) es el lenguaje estándar para gestionar y consultar bases de datos relacionales."),
Q("inf020","informatica","Un firewall tiene como función principal:",["Acelerar la conexión a internet","Proteger una red controlando el tráfico entrante y saliente","Diseñar páginas web","Almacenar archivos de gran tamaño"],1,"Un firewall es un sistema de seguridad que controla y filtra el tráfico de red para proteger contra accesos no autorizados."),

/* ============================================================
   PSICOLOGÍA
   ============================================================ */
Q("psi001","psicologia","La psicología se define como el estudio científico de:",["Solo las enfermedades mentales","La mente y el comportamiento","Únicamente el cerebro físico","Solo los sueños"],1,"La psicología es la disciplina científica que estudia la mente y el comportamiento humano."),
Q("psi002","psicologia","El condicionamiento clásico fue estudiado principalmente por:",["B.F. Skinner","Iván Pávlov","Sigmund Freud","Jean Piaget"],1,"Iván Pávlov, con sus experimentos con perros, es reconocido como pionero del condicionamiento clásico."),
Q("psi003","psicologia","El condicionamiento operante, basado en refuerzos y castigos, fue desarrollado principalmente por:",["Iván Pávlov","B.F. Skinner","Carl Jung","Jean Piaget"],1,"B.F. Skinner desarrolló la teoría del condicionamiento operante, centrada en cómo las consecuencias moldean el comportamiento."),
Q("psi004","psicologia","Sigmund Freud es reconocido principalmente por desarrollar la teoría de:",["El condicionamiento clásico","El psicoanálisis","Las etapas del desarrollo cognitivo","La jerarquía de necesidades"],1,"Sigmund Freud es el fundador del psicoanálisis, teoría centrada en los procesos inconscientes de la mente."),
Q("psi005","psicologia","Jean Piaget es conocido principalmente por su teoría sobre:",["La personalidad","Las etapas del desarrollo cognitivo en la infancia","El condicionamiento operante","Los trastornos mentales"],1,"Piaget propuso una teoría del desarrollo cognitivo dividida en etapas, desde la infancia hasta la adolescencia."),
Q("psi006","psicologia","Según la jerarquía de necesidades de Maslow, en la base de la pirámide se encuentran las necesidades:",["De autorrealización","Fisiológicas","Sociales","De estima"],1,"Las necesidades fisiológicas (como alimento y sueño) son la base de la pirámide de Maslow."),
Q("psi007","psicologia","La memoria a corto plazo se caracteriza por:",["Durar toda la vida","Retener información por un periodo breve y con capacidad limitada","No existir en los seres humanos","Ser idéntica a la memoria a largo plazo"],1,"La memoria a corto plazo retiene una cantidad limitada de información durante un periodo breve, antes de olvidarse o consolidarse en memoria a largo plazo."),
Q("psi008","psicologia","La disonancia cognitiva se refiere a:",["Un tipo de enfermedad neurológica","El malestar que se experimenta al sostener creencias o actitudes contradictorias","La pérdida total de la memoria","Un tipo de reflejo automático"],1,"La disonancia cognitiva es la incomodidad psicológica que surge al mantener simultáneamente creencias, actitudes o comportamientos contradictorios."),
Q("psi009","psicologia","El debate 'naturaleza vs crianza' (nature vs nurture) discute la influencia relativa de:",["La genética frente al ambiente en el desarrollo humano","La religión frente a la ciencia","El clima frente a la economía","La memoria frente al lenguaje"],0,"Este debate histórico discute en qué medida el comportamiento humano es determinado por la genética (naturaleza) o por el ambiente (crianza)."),
Q("psi010","psicologia","El conductismo, como corriente psicológica, se enfoca principalmente en:",["Los procesos inconscientes","El comportamiento observable y medible","Los sueños y su interpretación","La espiritualidad humana"],1,"El conductismo estudia el comportamiento observable, evitando especular sobre procesos mentales internos no medibles directamente."),
Q("psi011","psicologia","La teoría del apego, desarrollada por Bowlby y Ainsworth, estudia principalmente:",["El aprendizaje de idiomas","El vínculo emocional entre el bebé y su cuidador principal","Los trastornos alimenticios","La memoria a largo plazo"],1,"La teoría del apego analiza cómo se forma el vínculo emocional entre un infante y su cuidador principal, y su impacto en el desarrollo."),
Q("psi012","psicologia","La respuesta de 'lucha o huida' está asociada principalmente con:",["Un estado de relajación profunda","Una reacción fisiológica ante el estrés o el peligro percibido","El aprendizaje por repetición","La memoria a largo plazo"],1,"La respuesta de lucha o huida es una reacción fisiológica de activación ante una amenaza percibida, mediada en parte por la adrenalina."),
Q("psi013","psicologia","La psicología social estudia principalmente:",["El funcionamiento individual del cerebro","Cómo el comportamiento de las personas es influido por otros y por el contexto social","Los trastornos genéticos","La anatomía del sistema nervioso"],1,"La psicología social investiga cómo los pensamientos, sentimientos y comportamientos de las personas son influidos por la presencia y el contexto social."),
Q("psi014","psicologia","El coeficiente intelectual (CI) es una medida utilizada para:",["Medir la altura de una persona","Estimar ciertas capacidades cognitivas o intelectuales","Medir la presión arterial","Determinar el tipo de sangre"],1,"El CI es un puntaje derivado de pruebas estandarizadas que buscan estimar ciertas capacidades cognitivas."),
Q("psi015","psicologia","El refuerzo positivo en el condicionamiento operante consiste en:",["Quitar un estímulo desagradable para aumentar una conducta","Agregar un estímulo agradable para aumentar la probabilidad de una conducta","Castigar una conducta no deseada","Ignorar completamente una conducta"],1,"El refuerzo positivo aumenta la probabilidad de una conducta mediante la presentación de un estímulo agradable tras dicha conducta."),
Q("psi016","psicologia","El refuerzo negativo, a diferencia del castigo, consiste en:",["Aumentar una conducta al retirar un estímulo desagradable","Disminuir una conducta agregando un estímulo desagradable","Ser idéntico al castigo positivo","No tener ningún efecto sobre la conducta"],0,"El refuerzo negativo aumenta una conducta al retirar o evitar un estímulo aversivo, diferenciándose del castigo, que busca disminuir una conducta."),
Q("psi017","psicologia","La extinción, en el condicionamiento, se refiere a:",["El fortalecimiento de una conducta","La disminución gradual de una conducta aprendida al dejar de reforzarla","La aparición de una nueva conducta","Un tipo de trastorno mental"],1,"La extinción ocurre cuando una conducta previamente reforzada disminuye o desaparece al dejar de recibir el refuerzo."),
Q("psi018","psicologia","La psicología clínica se enfoca principalmente en:",["El estudio de la economía del comportamiento","La evaluación y el tratamiento de trastornos mentales y emocionales","El diseño de videojuegos","La administración de empresas"],1,"La psicología clínica se dedica a la evaluación, diagnóstico y tratamiento de trastornos psicológicos y emocionales."),
Q("psi019","psicologia","En un estudio experimental, la variable independiente es:",["La que se mide como resultado","La que el investigador manipula deliberadamente","Siempre el número de participantes","Un dato irrelevante para el estudio"],1,"La variable independiente es la que el investigador manipula intencionalmente para observar su efecto sobre otra variable."),
Q("psi020","psicologia","El hecho de que dos variables estén correlacionadas significa que:",["Una necesariamente causa a la otra","Existe una relación estadística entre ellas, sin que esto implique causalidad directa","No existe ninguna relación entre ellas","Ambas son idénticas"],1,"La correlación indica una relación estadística entre variables, pero no prueba por sí sola una relación de causa y efecto."),

/* ============================================================
   IDIOMAS
   ============================================================ */
Q("idi001","idiomas","Un sustantivo es una palabra que se utiliza para:",["Describir una acción","Nombrar personas, lugares, cosas o ideas","Modificar un verbo","Unir dos oraciones"],1,"El sustantivo es la clase de palabra que nombra personas, lugares, objetos, animales o ideas."),
Q("idi002","idiomas","Un verbo es una palabra que expresa principalmente:",["Una cualidad","Una acción o un estado","Un lugar","Una cantidad"],1,"El verbo expresa una acción, proceso o estado dentro de una oración."),
Q("idi003","idiomas","Un adjetivo cumple la función de:",["Nombrar un objeto","Describir o calificar a un sustantivo","Reemplazar un sustantivo","Unir dos verbos"],1,"El adjetivo es la palabra que describe o califica las características de un sustantivo."),
Q("idi004","idiomas","Un sinónimo es una palabra que tiene:",["El significado opuesto a otra","Un significado similar a otra","Ninguna relación con otra palabra","Un origen extranjero siempre"],1,"Un sinónimo es una palabra cuyo significado es similar o equivalente al de otra."),
Q("idi005","idiomas","Un antónimo es una palabra que tiene:",["Un significado similar a otra","Un significado opuesto a otra","La misma pronunciación que otra","El mismo origen que otra"],1,"Un antónimo es una palabra cuyo significado es contrario al de otra palabra."),
Q("idi006","idiomas","La concordancia entre sujeto y verbo implica que:",["El verbo debe coincidir en número y persona con el sujeto","El sujeto siempre va después del verbo","El verbo nunca cambia de forma","Solo aplica en preguntas"],0,"La concordancia gramatical exige que el verbo coincida en número (singular/plural) y persona con el sujeto de la oración."),
Q("idi007","idiomas","El tiempo pasado de un verbo se utiliza para describir:",["Una acción que ocurrirá en el futuro","Una acción que ya se completó","Una acción habitual en el presente","Una orden directa"],1,"El tiempo pasado indica que una acción ya ocurrió y se completó antes del momento presente."),
Q("idi008","idiomas","En inglés, las formas del verbo 'to be' en presente incluyen:",["Am, is, are","Was, were, been","Do, does, did","Have, has, had"],0,"En presente, el verbo 'to be' se conjuga como am, is y are, según el sujeto."),
Q("idi009","idiomas","El modo subjuntivo en español se utiliza frecuentemente para expresar:",["Hechos totalmente seguros","Duda, deseo o hipótesis","Solo el tiempo presente","Solo órdenes directas"],1,"El subjuntivo suele emplearse para expresar duda, deseo, posibilidad o hipótesis, en contraste con la certeza del indicativo."),
Q("idi010","idiomas","La gramática de un idioma se refiere a:",["Solo su vocabulario","El conjunto de reglas que rigen la estructura de ese idioma","Su alfabeto exclusivamente","Su origen histórico únicamente"],1,"La gramática comprende las reglas que organizan la estructura de las palabras y oraciones de un idioma."),
Q("idi011","idiomas","Un adverbio se utiliza para modificar principalmente a:",["Solo sustantivos","Verbos, adjetivos u otros adverbios","Solo pronombres","Solo artículos"],1,"El adverbio modifica el significado de un verbo, un adjetivo o incluso otro adverbio."),
Q("idi012","idiomas","Una preposición se usa para indicar principalmente:",["Una acción física","Una relación entre palabras, como lugar o tiempo (en, sobre, con)","El sujeto de una oración","El tiempo verbal"],1,"Las preposiciones (como 'en', 'sobre', 'con') expresan relaciones de lugar, tiempo, modo, entre otras, entre elementos de una oración."),
Q("idi013","idiomas","Un pronombre cumple principalmente la función de:",["Describir un objeto","Sustituir a un sustantivo","Modificar un adjetivo","Formar el plural de una palabra"],1,"El pronombre reemplaza a un sustantivo para evitar su repetición dentro del discurso."),
Q("idi014","idiomas","La conjugación verbal se refiere a:",["El significado de un verbo","Las distintas formas que adopta un verbo según tiempo, modo, número y persona","El sinónimo de un verbo","Un tipo de sustantivo"],1,"La conjugación son las variaciones que presenta un verbo según el tiempo, modo, número y persona gramatical."),
Q("idi015","idiomas","La fonética estudia principalmente:",["El significado de las palabras","Los sonidos del habla humana","La ortografía","La sintaxis"],1,"La fonética es la rama de la lingüística que estudia los sonidos físicos del habla."),
Q("idi016","idiomas","Una persona bilingüe se caracteriza por:",["No poder comunicarse en ningún idioma","Tener fluidez en dos idiomas","Hablar solo su lengua materna","No entender ningún idioma extranjero"],1,"Una persona bilingüe domina y se comunica con fluidez en dos idiomas."),
Q("idi017","idiomas","Un modismo (idiom) es una expresión que:",["Se interpreta siempre de forma literal","Tiene un significado figurado distinto al literal de sus palabras","Solo existe en un idioma, sin excepción","No tiene ningún uso en el habla cotidiana"],1,"Un modismo es una expresión cuyo significado figurado no se deduce directamente del significado literal de sus palabras."),
Q("idi018","idiomas","El estilo indirecto se utiliza para:",["Citar exactamente las palabras de alguien entre comillas","Reportar lo que alguien dijo, sin citarlo textualmente","Formular una pregunta directa","Expresar una orden"],1,"El estilo indirecto reformula lo dicho por otra persona sin reproducir textualmente sus palabras exactas."),
Q("idi019","idiomas","Un 'falso amigo' (false friend) en el aprendizaje de idiomas se refiere a:",["Una palabra idéntica en dos idiomas con el mismo significado","Una palabra parecida en dos idiomas pero con significados distintos","Un sinónimo perfecto entre dos idiomas","Una palabra que no existe en ningún idioma"],1,"Un falso amigo es una palabra que se parece a otra en un idioma distinto pero cuyo significado real es diferente, generando confusión."),
Q("idi020","idiomas","La sintaxis, como rama de la gramática, estudia principalmente:",["El significado aislado de las palabras","El orden y la combinación de las palabras dentro de una oración","La pronunciación de las palabras","El origen histórico de las palabras"],1,"La sintaxis analiza cómo se combinan y ordenan las palabras para formar oraciones gramaticalmente correctas."),


/* ============================================================
   ADMISIÓN — Plantel militar de medicina (enfoque EXANI-II)
   ============================================================ */
// Estas preguntas no son reactivos reales de CENEVAL ni de ninguna
// institución militar; son material de práctica original, diseñado
// para cubrir el tipo de contenido común en el EXANI-II para el
// área de la salud (razonamiento verbal, razonamiento matemático y
// comprensión lectora), más cultura general cívico-militar básica
// relevante para la admisión a un plantel militar/naval de medicina.
Q("adm001b","admision","Elige el antónimo de la palabra 'generoso':",["Amable","Tacaño","Alegre","Honesto"],1,"El antónimo de 'generoso' (que da con facilidad) es 'tacaño' (que evita compartir o gastar)."),
Q("adm002b","admision","Completa la analogía: Pájaro es a nido, como abeja es a:",["Flor","Panal","Miel","Polen"],1,"Así como el pájaro habita en un nido, la abeja vive y almacena su producción en un panal."),
Q("adm003b","admision","Un artículo cuesta $200 y tiene un descuento del 25%. ¿Cuál es su nuevo precio?",["$140","$150","$160","$175"],1,"El 25% de $200 es $50; al restar el descuento: $200 − $50 = $150."),
Q("adm004b","admision","Elige el sinónimo de la palabra 'perseverancia':",["Debilidad","Constancia","Indiferencia","Timidez"],1,"'Perseverancia' significa constancia o firmeza para continuar pese a las dificultades, muy afín a 'constancia'."),
Q("adm005b","admision","Completa la serie numérica: 3, 6, 12, 24, ___",["30","36","48","28"],2,"Cada número se obtiene multiplicando el anterior por 2: 24 × 2 = 48."),
Q("adm006b","admision","Si todos los aspirantes disciplinados aprueban el examen físico, y Juan es un aspirante disciplinado, ¿qué se puede concluir?",["Juan reprobará el examen físico","Juan aprobará el examen físico","No hay información suficiente","Juan no es aspirante"],1,"Es un silogismo válido: si la premisa general aplica a Juan (aspirante disciplinado), la conclusión particular se sigue lógicamente: Juan aprueba."),
Q("adm007b","admision","¿Cuál de las siguientes opciones NO pertenece al grupo por su significado?",["Disciplina","Honor","Lealtad","Desorden"],3,"'Desorden' es lo opuesto a los demás valores institucionales listados (disciplina, honor, lealtad), que comparten un sentido de compromiso y orden."),
Q("adm008b","admision","Un tren recorre 240 km en 3 horas a velocidad constante. ¿Cuál es su velocidad promedio?",["60 km/h","70 km/h","80 km/h","90 km/h"],2,"Velocidad = distancia entre tiempo: 240 km ÷ 3 h = 80 km/h."),
Q("adm009b","admision","Lee: 'La disciplina no es la ausencia de libertad, sino la base que permite ejercerla con responsabilidad.' Según el texto, la disciplina se presenta como:",["Un obstáculo para la libertad","La base que sostiene un ejercicio responsable de la libertad","Algo opuesto a la responsabilidad","Un tema sin relación con la libertad"],1,"El texto plantea explícitamente que la disciplina es la base que permite ejercer la libertad con responsabilidad, no su opuesto."),
Q("adm010b","admision","¿Cuáles son las tres fuerzas armadas que tradicionalmente conforman la defensa nacional de un país como México?",["Ejército, Fuerza Aérea y Guardia Nacional","Ejército, Fuerza Aérea y Armada (Marina)","Marina, Policía Federal y Ejército","Fuerza Aérea, Guardia Civil y Marina"],1,"En México, las Fuerzas Armadas están compuestas históricamente por el Ejército, la Fuerza Aérea y la Armada de México (Marina)."),
Q("adm011b","admision","Resuelve: si 3x − 7 = 14, ¿cuánto vale x?",["5","7","9","21"],1,"Sumando 7: 3x = 21; dividiendo entre 3: x = 7."),
Q("adm012b","admision","Elige la opción que completa correctamente: 'A pesar de ___ cansado, terminó su entrenamiento.'",["Estar","Está","Esté","Estaba"],0,"Después de 'a pesar de' se usa el infinitivo del verbo ('estar'), no una forma conjugada."),
Q("adm013b","admision","¿Cuál es el sinónimo más adecuado de 'vocación' en el contexto de elegir una carrera?",["Obligación","Inclinación o llamado personal hacia una actividad","Rechazo","Casualidad"],1,"La 'vocación' se refiere a una inclinación o llamado personal hacia determinada actividad o profesión."),
Q("adm014b","admision","Un laboratorio necesita diluir una solución al doble de su volumen para reducir su concentración a la mitad. Si tiene 250 ml de solución, ¿cuántos ml de agua debe agregar?",["125 ml","250 ml","500 ml","750 ml"],1,"Para duplicar el volumen total (de 250 ml a 500 ml), debe agregar exactamente 250 ml de agua."),
Q("adm015b","admision","¿Cuál de las siguientes palabras es un antónimo de 'disciplina'?",["Orden","Constancia","Indisciplina","Rigor"],2,"El antónimo directo de 'disciplina' es 'indisciplina', que implica falta de orden o control."),
Q("adm016b","admision","En una fila de aspirantes, María está justo detrás de Pedro y justo delante de Luis. Si Pedro es el tercero en la fila, ¿qué lugar ocupa Luis?",["Cuarto","Quinto","Segundo","Primero"],1,"Si Pedro es tercero, María (detrás de él) es cuarta, y Luis (detrás de María) es quinto."),
Q("adm017b","admision","¿Cuál es el propósito principal de un examen de admisión como el EXANI-II?",["Evaluar únicamente conocimientos de un solo tema","Evaluar habilidades y conocimientos generales relevantes para el ingreso a estudios superiores","Sustituir por completo la entrevista personal","Medir exclusivamente la condición física del aspirante"],1,"El EXANI-II está diseñado para evaluar habilidades académicas (razonamiento verbal y matemático) y conocimientos relevantes para el ingreso a educación superior."),
Q("adm018b","admision","Si un examen tiene 120 preguntas y un aspirante contesta correctamente el 85%, ¿cuántas preguntas acertó?",["96","102","98","110"],1,"El 85% de 120 se calcula como 0.85 × 120 = 102 preguntas correctas."),
Q("adm019b","admision","¿Cuál es el antónimo de 'coherente'?",["Lógico","Contradictorio","Ordenado","Claro"],1,"'Coherente' implica lógica y consistencia interna; su antónimo es 'contradictorio'."),
Q("adm020b","admision","Un aspirante debe leer 180 páginas en 4 días, dedicando la misma cantidad cada día. ¿Cuántas páginas debe leer diariamente?",["35","40","45","50"],2,"180 páginas entre 4 días = 45 páginas por día."),
Q("adm021b","admision","Elige la palabra que completa mejor la oración: 'El aspirante mostró gran ___ durante la prueba física, sin rendirse pese al cansancio.'",["Indiferencia","Resistencia","Debilidad","Distracción"],1,"'Resistencia' encaja con la idea de no rendirse pese al cansancio; las demás opciones contradicen el sentido de la oración."),
Q("adm022b","admision","Si la razón entre aspirantes admitidos y no admitidos es de 1 a 4, y se presentaron 500 aspirantes, ¿cuántos fueron admitidos?",["80","100","125","150"],1,"La razón 1:4 implica 1 admitido por cada 4 no admitidos, es decir, 1 de cada 5 en total. 500 ÷ 5 = 100 admitidos."),
Q("adm023b","admision","¿Qué habilidad evalúa principalmente un ejercicio de comprensión lectora en un examen de admisión?",["Memorización de fórmulas","La capacidad de entender, interpretar y analizar un texto","La velocidad para escribir","El conocimiento de un segundo idioma exclusivamente"],1,"Los ejercicios de comprensión lectora evalúan la capacidad de entender, interpretar y analizar la información de un texto."),
Q("adm024b","admision","Elige el sinónimo de 'íntegro' en el contexto de valores personales:",["Corrupto","Honesto y recto","Indiferente","Distraído"],1,"'Íntegro' se refiere a una persona honesta, recta y coherente entre lo que piensa, dice y hace."),
Q("adm025b","admision","En una prueba de 50 preguntas, cada acierto suma 2 puntos y cada error resta 0.5 puntos. Si un aspirante acierta 40 y falla 10, ¿cuál es su puntaje total?",["75","70","65","80"],0,"40 aciertos × 2 puntos = 80; 10 errores × 0.5 puntos = 5 puntos restados; 80 − 5 = 75 puntos."),

/* ============================================================
   OTRAS MATERIAS (cultura general)
   ============================================================ */
Q("otr001","otras","¿Cuál es el océano más grande del mundo?",["Atlántico","Índico","Pacífico","Ártico"],2,"El océano Pacífico es el más extenso y profundo de los océanos del planeta."),
Q("otr002","otras","Según el modelo de siete continentes, ¿cuántos continentes se reconocen?",["5","6","7","8"],2,"El modelo de siete continentes reconoce: África, América del Norte, América del Sur, Antártida, Asia, Europa y Oceanía."),
Q("otr003","otras","¿Cuál es el órgano más grande del cuerpo humano?",["El hígado","El cerebro","La piel","El corazón"],2,"La piel, considerando toda su superficie, es el órgano más extenso del cuerpo humano."),
Q("otr004","otras","¿Quién pintó la Mona Lisa?",["Pablo Picasso","Leonardo da Vinci","Vincent van Gogh","Miguel Ángel"],1,"La Mona Lisa fue pintada por Leonardo da Vinci a inicios del siglo XVI."),
Q("otr005","otras","¿Quién escribió la novela 'Don Quijote de la Mancha'?",["Gabriel García Márquez","Miguel de Cervantes","Pablo Neruda","Jorge Luis Borges"],1,"'Don Quijote de la Mancha' fue escrita por Miguel de Cervantes Saavedra."),
Q("otr006","otras","¿Cuántos jugadores conforman un equipo de fútbol soccer en la cancha?",["9","10","11","12"],2,"Un equipo de fútbol tiene 11 jugadores en el campo, incluyendo al portero."),
Q("otr007","otras","¿Cuál es la montaña más alta del mundo?",["K2","Aconcagua","Monte Everest","Kilimanjaro"],2,"El Monte Everest, en la cordillera del Himalaya, es la montaña más alta sobre el nivel del mar."),
Q("otr008","otras","¿Cuál es el planeta más cercano al Sol?",["Venus","Mercurio","Tierra","Marte"],1,"Mercurio es el planeta más cercano al Sol en el sistema solar."),
Q("otr009","otras","¿Qué vitamina se sintetiza principalmente por exposición a la luz solar?",["Vitamina A","Vitamina C","Vitamina D","Vitamina K"],2,"La piel sintetiza vitamina D al exponerse a la luz solar (rayos UVB)."),
Q("otr010","otras","¿Quién es reconocido como el inventor del teléfono?",["Thomas Edison","Alexander Graham Bell","Nikola Tesla","Guillermo Marconi"],1,"Alexander Graham Bell es reconocido históricamente como el inventor del teléfono."),
Q("otr011","otras","¿Cuál es la moneda oficial de México?",["Dólar","Peso mexicano","Euro","Quetzal"],1,"La moneda oficial de México es el peso mexicano."),
Q("otr012","otras","¿A qué temperatura se congela el agua a nivel del mar?",["0°C","10°C","-10°C","100°C"],0,"El agua se congela a 0°C (32°F) a presión atmosférica estándar."),
Q("otr013","otras","¿A qué temperatura hierve el agua a nivel del mar?",["50°C","75°C","90°C","100°C"],3,"El agua hierve a 100°C (212°F) a nivel del mar."),
Q("otr014","otras","¿Cuántos días tiene un año bisiesto?",["364","365","366","367"],2,"Un año bisiesto tiene 366 días, con un día adicional (29 de febrero) cada 4 años aproximadamente."),
Q("otr015","otras","¿Cuál es el desierto más grande del mundo (considerando desiertos fríos)?",["Sahara","Gobi","Antártida","Atacama"],2,"Considerando su definición climática (baja precipitación), la Antártida es el desierto más extenso del mundo."),
Q("otr016","otras","¿Qué compositor es conocido por la 'Novena Sinfonía'?",["Mozart","Beethoven","Bach","Chopin"],1,"Ludwig van Beethoven compuso la célebre Novena Sinfonía, que incluye el 'Himno a la Alegría'."),
Q("otr017","otras","¿Cada cuántos años se celebran los Juegos Olímpicos de verano?",["2 años","3 años","4 años","5 años"],2,"Los Juegos Olímpicos de verano se celebran cada 4 años."),
Q("otr018","otras","¿Cuáles son los tres macronutrientes principales de la dieta humana?",["Vitaminas, minerales y agua","Carbohidratos, proteínas y grasas","Fibra, agua y sal","Calcio, hierro y potasio"],1,"Los tres macronutrientes principales son los carbohidratos, las proteínas y las grasas (lípidos)."),
Q("otr019","otras","¿Dónde se encuentra la sede principal de la Organización de las Naciones Unidas?",["Ginebra","París","Nueva York","Londres"],2,"La sede principal de la ONU se ubica en la ciudad de Nueva York, Estados Unidos."),
Q("otr020","otras","¿Cuál es el idioma con mayor número de hablantes nativos en el mundo?",["Inglés","Español","Mandarín (chino)","Hindi"],2,"El mandarín (chino) tiene el mayor número de hablantes nativos en el mundo."),

/* ============================================================
   EXAMEN PSICOMÉTRICO (material de práctica orientativo)
   ============================================================ */
// Aviso importante: estas preguntas son material de práctica ORIGINAL,
// inspirado en formatos comunes de evaluación psicométrica (razonamiento
// lógico, numérico, verbal y de juicio situacional). NO son un
// instrumento psicológico validado ni reemplazan una evaluación
// psicométrica profesional real, que debe ser aplicada e interpretada
// por un especialista. Úsalas solo como calentamiento de formato.
Q("psic001","psicometrico","Completa la serie: 2, 6, 12, 20, 30, ___",["36","40","42","48"],2,"Las diferencias entre términos aumentan de 2 en 2 (4,6,8,10,12): 30+12=42."),
Q("psic002","psicometrico","Si 'correr' es a 'piernas' como 'escribir' es a:",["Ojos","Manos","Boca","Oídos"],1,"Así como correr se realiza principalmente con las piernas, escribir se realiza principalmente con las manos."),
Q("psic003","psicometrico","¿Qué número no pertenece a la serie: 3, 9, 27, 40, 81?",["9","27","40","81"],2,"La serie sigue el patrón ×3 (3, 9, 27, 81); el 40 rompe ese patrón."),
Q("psic004","psicometrico","Ante una situación de trabajo en equipo donde un compañero comete un error que afecta la tarea grupal, la actitud más adecuada suele ser:",["Ignorar el error para evitar el conflicto","Señalar el error de forma respetuosa y proponer una solución conjunta","Culpar públicamente al compañero","Reportarlo sin hablar primero con él"],1,"Una actitud colaborativa y madura implica comunicar el problema con respeto y buscar una solución en conjunto, en lugar de evitarlo o generar conflicto innecesario."),
Q("psic005","psicometrico","¿Cuál de las siguientes palabras no pertenece al grupo?",["Rápido","Veloz","Ágil","Lento"],3,"'Lento' es antónimo de las otras tres palabras, que son sinónimas entre sí (rapidez)."),
Q("psic006","psicometrico","Si hoy es miércoles, ¿qué día será dentro de 10 días?",["Viernes","Sábado","Domingo","Lunes"],1,"10 días equivalen a 1 semana (7 días) + 3 días. Miércoles + 7 = miércoles; + 3 días más = sábado."),
Q("psic007","psicometrico","Ante una instrucción poco clara de un superior, la actitud más adecuada es:",["Actuar de inmediato según tu propia interpretación, sin verificar","Pedir una aclaración antes de proceder, de forma respetuosa","Ignorar la instrucción por completo","Esperar a que alguien más la resuelva"],1,"Pedir una aclaración de forma respetuosa evita errores por malentendidos y refleja responsabilidad, sin ser pasivo ni actuar de forma impulsiva."),
Q("psic008","psicometrico","Encuentra el intruso: manzana, plátano, zanahoria, naranja.",["Manzana","Plátano","Zanahoria","Naranja"],2,"La zanahoria es una verdura/raíz, mientras que las demás opciones son frutas."),
Q("psic009","psicometrico","Un cubo tiene 6 caras. Si se pinta completamente de rojo y luego se corta en 27 cubos pequeños iguales, ¿cuántos cubos pequeños no tendrán ninguna cara pintada?",["0","1","6","8"],1,"Al cortar un cubo 3x3x3 en 27 cubos, solo el cubo central (rodeado por todos los lados) queda sin caras pintadas: 1 cubo."),
Q("psic010","psicometrico","Frente a una tarea que se percibe como muy difícil, la actitud más constructiva suele ser:",["Evitarla por completo","Dividirla en pasos más pequeños y manejables, y avanzar de forma constante","Realizarla de forma apresurada sin planear","Delegarla siempre a otra persona"],1,"Dividir una tarea compleja en pasos pequeños y manejables es una estrategia efectiva para afrontar la dificultad de forma constructiva."),
Q("psic011","psicometrico","¿Qué número sigue en la serie: 1, 4, 9, 16, 25, ___? (son cuadrados perfectos)",["30","36","42","49"],1,"La serie corresponde a los cuadrados de los números naturales (1²,2²,3²,4²,5²); el siguiente es 6²=36."),
Q("psic012","psicometrico","Al recibir una crítica constructiva sobre tu desempeño, la respuesta más madura es:",["Reaccionar a la defensiva de inmediato","Escuchar, reflexionar sobre lo dicho, y considerar los puntos válidos para mejorar","Ignorarla por completo","Responder con otra crítica hacia quien la hizo"],1,"Escuchar y reflexionar sobre la crítica, sin reaccionar defensivamente, refleja madurez emocional y disposición a mejorar."),
Q("psic013","psicometrico","¿Cuál de las siguientes opciones completa la analogía? Médico es a hospital, como maestro es a:",["Oficina","Escuela","Fábrica","Tribunal"],1,"Así como el médico ejerce típicamente en un hospital, el maestro ejerce típicamente en una escuela."),
Q("psic014","psicometrico","Tienes múltiples tareas pendientes con distintos niveles de urgencia. La estrategia más recomendable es:",["Realizarlas en el orden en que llegaron, sin importar la urgencia","Priorizar según urgencia e importancia antes de comenzar","Realizar primero las más fáciles, sin importar la urgencia","Posponer todas hasta el último momento"],1,"Priorizar tareas según su urgencia e importancia es una estrategia recomendada de gestión del tiempo."),
Q("psic015","psicometrico","Completa la serie de letras: A, C, E, G, ___",["H","I","J","K"],1,"La serie avanza saltando una letra cada vez (A_C_E_G): después de G sigue I."),
];
